### ISSUE TITLE
[Feature] Adjust liveness- and readiness probe defaults and add a stop handler

### ISSUE THREAD

**Issue by libuweber** [ergon/airlock-helm-charts#65]
## Description
- Changes liveness- and readiness probe default values
- Adds a preStop handler to give time for finishing up existing client connections/requests before shutting down. (This has the effect that shutting down pods takes longer, but it will be a clean shutdown from a user perspective, assuming there are other pods to handle the traffic)

## Versions
 - Microgateway: 1.0
 - Helm chart: 0.6.0

**Comment by dieti80** [comment]
@libuweber 
* The changes for the `preStop handler` are fine.
* VSHN said that we should stick to the default values for liveness and readiness probes. Did they mean we have to configure them explicitly or just remove them from our configuration? Did they suggest to configure explicitly failureThreshold and timeoutSeconds?
