### ISSUE TITLE
Rename the TLS files for VH 

### ISSUE THREAD

**Issue by jbe99** [ergon/airlock-helm-charts#7]
https://github.com/ergon/airlock-helm-charts/blob/7f82442c55ae1970bd6c0f31fba1b3e72d55b7bc/charts/microgateway/templates/configmap.yaml#L97

It affects these three lines:

          certificate_file: /secret/tls/tls.crt
          privatekey_file: /secret/tls/tls.key
          ca_chain_file: /secret/tls/ca.crt

Change the file name according to AP-27866. Wait first until requirement spec. of AP-27866 is ok.

**Comment by dieti80** [comment]
There is a bug. What if tlsSecretName is used for Back-end connection but not for Virtual Host?

We should not set explicitly the _file or check if the secret contains those files.

Once again, we should wait for the outcom of AP-27866.

**Comment by dieti80** [comment]
AP-27866 is implemented and it is clear now what the name of those files are:

||Kind of setting||Old path||New path||
|Zertifikat|/secret/certificate|/secret/tls/frontend-server.crt|
|Private Key|/secret/privatekey|/secret/tls/frontend-server.key|
|CA Chain|/secret/ca-chain|/secret/tls/frontend-server-ca.crt|
